apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prueba
  template:
    metadata:
      labels:
        app: prueba
    spec:
      containers:
      - name: prueba
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080